### ISSUE TITLE
[BUG] ValidationContext's Validations property is always empty

### ISSUE THREAD

**Issue by Micha-kun** [reactiveui/ReactiveUI.Validation#31] opened 2019-07-25 17:25 UTC
**Describe the bug**

I'm working in a **WinForms** project, having the **ViewModel** project as an **F# project**, and I'm try to use **ReactiveUI.Validations** as saw in your login sample, but when I try to bind the same property on View with **BindValidation**, the library throws an expection because cannot find any validation by index. Then, after debugging step by step, even when the private field **_validationSource** have items in it, it doesn't propage to the **Validations** property and always is empty.

Special Characteristics:
- **ReactiveUI.Validation** version is **1.2.1**
- Projects are **.NET Framework 4.7.2**
- WinForms project is a **C# project**.
- ViewModel project is an **F# project**.
- I've created an abstract **ValidatableReactiveObject** class that implements the **ISupportsValidation** interface, and then used on other ViewModels.
- Validation works if I get the **ValidationHelper** result and bind my controls to those, but I have many bindable validations and I prefer to avoid to have those helpers in the way if I can...

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

- OS:        **Windows 10**
- **Visual Studio 2017**
- Version    **1.2.1**
- Device:   

**Additional context**

Repository Sample: **https://github.com/Micha-kun/ReactiveUI.Validation.BugTest**

**PD: I'll fill later with more data, sorry**

**Comment by glennawatson** [comment] 2019-07-26 03:44
Hi @Micha-kun are you able to provide a small repository with a sample of your problem?

**Comment by Micha-kun** [comment] 2019-07-26 06:33
Hi @glennawatson I filled about the bug with new info. I'll try to make that repository later and share with you.

Thank you

**Comment by Micha-kun** [comment] 2019-07-26 11:04
Here is the repository sample:

https://github.com/Micha-kun/ReactiveUI.Validation.BugTest

**Comment by Micha-kun** [comment] 2019-07-26 12:22
I found that if I create the ValidationContext instance with **RxApp.TaskpoolScheduler**, it works as expected. By default it uses **RxApp.MainThreadScheduler** and, with this scheduler it doesn't refresh... Maybe in WinForms it requires to use TaskpoolScheduler as default?

**Comment by miqueljuan** [comment] 2019-08-01 16:40
I found the same problem working in WPF, if i use the ValidationContext with ** RxApp.TaskpoolScheduler ** on my abstract class it works as expected, else throws ArgumentOutOfRangeException. 

Without using an abstract class, with all the properties declared on the validated ViewModel it works with RxApp.MainThreadScheduler. 

Special Characteristics:

- ReactiveUI.Validation  version is 1.2.1
- Project target .NET Framework 4.7.2
- WPF project is a C# project.
- ViewModel project is a C# project.

**Comment by StanleyGoldman** [comment] 2019-09-27 22:07
I recently hit this issue and I have a repro: https://github.com/StanleyGoldman/UnderstandReactiveUIProblem/tree/validation

**Comment by StanleyGoldman** [comment] 2019-09-27 22:15
Can confirm workaround works: https://github.com/StanleyGoldman/UnderstandReactiveUIProblem/tree/validation-fix

**Comment by kagerouttepaso** [comment] 2019-10-08 06:19
If you set the ViewModel after resolving the main thread queue, no exception will occur.

``` cs
    internal class Program
    {
        [STAThread]
        public static void Main()
        {
            var app = new App();
            var vm = new MainWindowViewModel();
            var window = new MainWindowView();

            Service.DoEvennts();
            window.ViewModel = vm;

            app.Run(window);
        }
    }

    public static class Service
    {
        [SecurityCritical]
        [SecurityPermission(SecurityAction.Demand, Flags = SecurityPermissionFlag.UnmanagedCode)]
        public static void DoEvennts()
        {
            DispatcherFrame frame = new DispatcherFrame();
            Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.Background,
                new DispatcherOperationCallback(ExitFrames), frame);
            Dispatcher.PushFrame(frame);
        }

        public static object ExitFrames(object f)
        {
            ((DispatcherFrame)f).Continue = false;
            return null;
        }
    }

```

**Comment by kagerouttepaso** [comment] 2020-01-15 13:39
I want IObservableList <IValidationComponent> to be published as a public property.For simple collection access, you can use IObservableList <IValidationComponent> .Items.
The problem of scheduler is caused by using ReadOnlyObservableCollection <IValidationComponent>.I think that scheduler-aware coding, including creation of ReadOnlyObservableCollection, should be done by library users.
Currently I use the following extension methods for binding to a View.

``` cs 
public static IObservable<IList<ValidationState>> ResolveValidationStatusChanges<TViewModel, TViewModelProperty>(
    this TViewModel vm,
    Expression<Func<TViewModel, TViewModelProperty>> viewModelProperty,
    bool exclusively = true)
       where TViewModel : ReactiveObject, IValidatableViewModel
{
    var field = typeof(ValidationContext).GetField("_validationSource", BindingFlags.InvokeMethod | BindingFlags.NonPublic | BindingFlags.Instance);
    var sourcelist = (SourceList<IValidationComponent>)field.GetValue(vm.ValidationContext);
    IObservableList<IValidationComponent> observableList = sourcelist.AsObservableList();

    return observableList
        .Connect()
        .ToCollection()
        .Select(c => Observable.CombineLatest(c
            .OfType<BasePropertyValidation<TViewModel, TViewModelProperty>>()
            .Where(x => x.ContainsProperty(viewModelProperty, exclusively))
            .Select(x => x.ValidationStatusChange)))
        .Switch();
}
```

``` cs
ViewModel.ResolveValidationStatusChanges(x => x.IpAddress)
    .Select(x => string.Join(",", x.Where(b => !b.IsValid).SelectMany(b => b.Text)))
    .ObserveOn(RxApp.MainThreadScheduler)
    .BindTo(this, v => v._test.Text)
    .DisposeWith(d);
```

**Comment by worldbeater** [comment] 2020-07-17 15:53
This should have been fixed in https://github.com/reactiveui/ReactiveUI.Validation/pull/82. With `ReactiveUI.Validation` from the `main` branch, the `ArgumentOutOfRangeException` is no longer thrown in `BindValidation`, and the `ValidationContext` is  performing as expected, at least in my WPF playground :tada:

**Closed** 2020-07-17 16:18 UTC
Labels: bug, help wanted
